[unix_http_server]
file=/run/supervisord.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/run/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[program:horizon]
process_name=%(program_name)s
command=/usr/local/bin/php /app/artisan horizon
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/app/storage/logs/horizon.log
stopwaitsecs=3600

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true

[supervisorctl]
serverurl=unix:///run/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = supervisord.d/*.ini
